### PR TITLE
add maxHeight props

### PR DESCRIPTION
**Pull request by linwenchao**

### CODE REVIEW

**Comment by vivaxy** [comment]
Please provide information about how to and when to use `maxHeight`.

**Comment by vivaxy** [comment]
Closing for no response.

**Comment by yokada0807** [comment]
Thanks for the nice work :)
I want this feature so that the image height may not be extremely long.

**Comment by vivaxy** [comment]
Closed for conflict

**Comment by vivaxy** [comment]
@yokada0807 Thanks for your suggestion. `maxHeight` have been implemented at v3.2.0

**Pull request closed without merging**
